{
    "name": "Hệ thống quản lý thư viện",
    "summary": "Quản lý sách, bạn đọc, mượn trả, bảng điều khiển và báo cáo.",
    "version": "16.0.1.0.0",
    "category": "Education",
    "author": "QLTV",
    "website": "",
    "license": "LGPL-3",
    "depends": ["base", "web", "mail", "stock", "account"],
    "data": [
        "security/library_security.xml",
        "security/ir.model.access.csv",
        "security/library_record_rules.xml",
        "data/cron_data.xml",
        "data/account_data.xml",
        "views/library_book_views.xml",
        "views/library_book_kanban_views.xml",
        "views/library_book_category_views.xml",
        "views/library_book_copy_views.xml",
        "views/library_reader_views.xml",
        "views/library_borrow_views.xml",
        "views/library_borrow_kanban_views.xml",
        "views/library_reader_views_self.xml",
        "views/dashboard_views.xml",
        "views/menu_views.xml",
        "data/users_data.xml",
        "report/borrow_report_template.xml",
        "report/borrow_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "web/static/lib/Chart/Chart.js",
            "QLTV/static/src/js/dashboard_action.js",
            "QLTV/static/src/js/book_list_extension.js",
            "QLTV/static/src/js/kanban_extension.js",
            "QLTV/static/src/js/pivot_extension.js",
            "QLTV/static/src/js/graph_extension.js",
            "QLTV/static/src/scss/dashboard.scss",
            "QLTV/static/src/scss/library.scss",
            "QLTV/static/src/xml/dashboard_templates.xml",
            "QLTV/static/src/xml/dashboard_cards.xml",
            "QLTV/static/src/xml/dashboard_charts.xml",
            "QLTV/static/src/xml/kanban_templates.xml",
            "QLTV/static/src/xml/list_templates.xml",
            "QLTV/static/src/xml/pivot_templates.xml",
            "QLTV/static/src/xml/graph_templates.xml",
            "QLTV/static/src/js/vn_money_widget.js",
            "QLTV/static/src/js/vn_datetime_widget.js",
            "QLTV/static/src/js/password_toggle_widget.js",
            "QLTV/static/src/xml/widget_templates.xml",
        ],
    },
    "demo": [
        "demo/demo_data.xml",
    ],
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
}
